version: '3'

services:
  web:
    container_name: s41-web-service-flask-postgres
    image: s41-web-service-flask-postgres:latest
    restart: always
    build: .
    # links:
    #   - postgres:postgres
    links:
      - postgres
    ports:
      - 9000:8080
    env_file: 
      - .env
    volumes:
      - web-data:/etc/nginx

  data:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    command: "true"

  postgres:
    container_name: db_postgres
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    restart: always
    image: nginx:1.18.0-alpine
    # build: ./nginx
    ports:
      - "80:80"
    volumes:
      - web-data:/usr/src/app/static
      - web-data:/etc/nginx
    links:
      - web:web

volumes:
  db-data:
  web-data:
